### ISSUE TITLE
PXE_TFTP_PATH behavior different in rear-1.17

### ISSUE THREAD

**Issue by gdha** [brainupdaters/drlm#12]
Could someone have a look at issue in rear - https://github.com/rear/rear/issues/570
I just wonder if DRLM is now broken and if yes, please make a pull request and we will prepare a new rear-1.17.1 release asap.
thanks,
Gratien

**Comment by didacog** [comment]
Hi Gratien,

i will start looking this issue later today.

Regards,
Didac

**Comment by didacog** [comment]
Hi Gratien,

This behaviour remains the same since rear 1.16 version. 
In 1.17 we only added OUTPUT_PREFIX_PXE=$OUTPUT_PREFIX (default) 
to not change any standard procedure using $OUTPUT_PREFIX.

See this commit:

https://github.com/rear/rear/commit/db3fe677a15a82b4488153993ecd7afb09078b1a

Added $OUTPUT_PREFIX to kernel and initrd lines, because if not present, PXE config file never found the location of kernel and initrd files. 

by default ReaR creates $OUTPUT_PREFIX=$HOSTNAME folder to remote location to store the PXE output files. And never found if /$PXE_KERNEL and /$PXE_INITRD * because they are stored on  SOME_LOCATION/$OUTPUT_PREFIX/$[PXE_KERNEL|PXE_INITRD].

We never need to  use/overwrite the $PXE_TFTP_PATH variable.

Maybe if OUTPUT_PREFIX_PXE="" is set on site.conf solve this configuration issue rear/rear#570

if  OUTPUT_PREFIX_PXE="" 

81_create_pxelinux_cfg.sh result:

	kernel /$PXE_KERNEL
	append initrd=/$PXE_INITRD root=/dev/ram0 vga=normal rw $KERNEL_CMDLINE

This will maintain the rear-1.15 behaviour. And changes nothing regarding OUTPUT_PREFIX stuff
Regards,
Didac

**Comment by didacog** [comment]
Now ReaR has OUTPUT_PREFIX_PXE="" in default.conf 
https://github.com/rear/rear/commit/cbf402b4b4cab7260e17d94bf3d990877fdd6cd0

In DRLM client configurations must be set this to OUTPUT_PREFIX_PXE="OUTPUT_PREFIX"
