### ISSUE TITLE
Automatically create the directory structure during installation

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#26]
In order to make and easier installation the directory structure by default can be generated automatically.
 
Directory structure:
$ mkdir -p /var/lib/drlm/arch
$ mkdir -p /var/lib/drlm/store/pxelinux.cfg

pxelinux.0:
$ cp -p /usr/lib/syslinux/pxelinux.0 /var/lib/drlm/store/
$ chmod 755 /var/lib/drlm/store/pxelinux.0

**Comment by didacog** [comment]
This changed a little with new GRUB2 netboot, now the directory structure will be created if required.

Anyway is recommended that $ARCHDIR (/var/lib/drlm/arch) will be a separated Filesystem and not just a directory, in order to prevent filling of /var filesystem with dr images.

This issue can be closed.
