### ISSUE TITLE
DRLM Grub2 PXE file: forced console=ttyS0 in kernel options

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#52]
In the Grub loader is hardcoded console=ttyS0,115200n8 this can cause problems booting in a system without serial ports, because in the  sysinit.service of the ReaR rescue mode there is the parameter StandardInput=tty and the output /dev/console is not writable.

**Comment by didacog** [comment]
This issue is now solved, we gather the kernel options from ReaR, also there are no more harcoded PXE filenames in the code, this give us the capacity to not force to set client hostnames as drlm client names and now we support lzma (initrd.xz) compression (see https://github.com/rear/rear/pull/1182).

Regards,
