### ISSUE TITLE
docker container

### ISSUE THREAD

**Issue by razorfish-sl** [brainupdaters/drlm#63]
#### Disaster Recovery Linux Manager (DRLM) Issue Template

Can we have something that can be put into a docker container.
trying to install this inside  centos or other docker os containers seems not to work, due to  systemd problems.

**Comment by didacog** [comment]
Hello @razorfish-sl,

He didn't tested anything to use DRLM in a container, so it is normal that does not work.
If you are trying it and you can solve these systemd problems we will be very happy to see your PR providing support for containers for DRLM. ;) 

Regards,
Didac

**Comment by razorfish-sl** [comment]
building with separate containers for each part
it's a big job..... many parts which need ad in-depth knowledge of the system  (ports etc)

I looked at an OS container with it in (centos7), then load in DRLM
 but docker site is clear it disables "systemd" etc means building a special OS version for docker...
and a lot of overhead for a full os

**Comment by didacog** [comment]
Well, yes we know that should be hard to work on it, and this is why we didn't planned to containerize DRLM yet... 
Maybe you can attach your findings to this issue, and it would be an starting point for the future work on it... ;)

**Comment by db260179** [comment]
Hi, I'll add my pull request for my docker version of drlm. The systemd part is tricky but there is a work around for all of this.

I send in the next few days

**Comment by didacog** [comment]
Hi @db260179,
Can you explain me a little bit what is your proposal to run DRLMv2 in docker?
Do you have something to see? a branch? repo?
Did you tested it?
I'm looking forward to talk on this topic with you ;)

Regards!

**Comment by didacog** [comment]
@db260179 I see now your comment, I was typing... and did not see it.

Ok, I'll wait for the PR then.

Regards!

**Comment by db260179** [comment]
> Hi @db260179,
> Can you explain me a little bit what is your proposal to run DRLMv2 in docker?
> Do you have something to see? a branch? repo?
> Did you tested it?
> I'm looking forward to talk on this topic with you ;)
> 
> Regards!

https://github.com/db260179/drlm/commit/acae1ddcc957ce48ff5357d14316bed8dbe7b027

So this is a cleaned up version i've submitted to my repo.
I'm using debian 10 as a base image

The NFS, TFTPD and DHCP services are treated as normal init scripts your usr/lib functions seem to cater for both systemd and openrc so that was straight forward.

I'm still undecided if using supervisord would be better to manage the processes for the NFS,TFTPD etc

Because it is debian based I use deb build process the used that deb file to install to the container - this can be changed to just install directly?

The docker container has to use the privileged mode and net host mode for these services to work

Running drlm commands are straight forward by just docker exec -it drlm-server drlm help

Let me know what you think?

**Comment by didacog** [comment]
Hi @db260179,

Looks good! 

I think that supervisord or systemd should be needed to restart any failed service in the container.

Will be possible to use <pre>make install</pre>  but we need to check if something is missing from the pre/post install scripts of deb packaging.

making an alias to the host:  drlm="docker exec -it drlm-server drlm' will be good also :P

Volumes for ARCHDIR (/var/lib/drlm/arch) and database location (/var/lib/drlm) should be provided also to keep the persistence. Maybe better to use only one volume /var/lib/drlm for all?

Also we are looking for alternatives to provide other boot methods, that will not require dhcp/tftp in drlm and give the possibility to run dockerized drlm without host networking and not being forced to be attached at one host.  

I've just took a fast look, but seems a really good starting point!! I'm gonna test your repo this week and come back with the results.

Thanks for contributing to the DRLM project!

Regards,
Didac

**Comment by db260179** [comment]
> Hi @db260179,
> 
> Looks good!

Thanks!

> 
> I think that supervisord or systemd should be needed to restart any failed service in the container.
> 

supervisord is the better solution for docker, systemd is a pain

> Will be possible to use
> 
> make install

Yeh i said before this would be ideal to do in the build of the docker image rather than using the deb process.

> but we need to check if something is missing from the pre/post install scripts of deb packaging.
> making an alias to the host: drlm="docker exec -it drlm-server drlm' will be good also :P

Ideally starting via a docker compose would be better - naming of containers will be consistent then using network aliases.

> 
> Volumes for ARCHDIR (/var/lib/drlm/arch) and database location (/var/lib/drlm) should be provided also to keep the persistence. Maybe better to use only one volume /var/lib/drlm for all?
> 

Yeh, for a first attempt i just did a bind to host - but yes docker volumes are best used for this. I would offer the choice, it doesn't matter really as volumes can be changed regardless

> Also we are looking for alternatives to provide other boot methods, that will not require dhcp/tftp in drlm and give the possibility to run dockerized drlm without host networking and not being forced to be attached at one host.

Using docker in a compose can separate the need to have these services on one container also helps towards the docker swarm, kubernetes platforms if services are seperated.

> 
> I've just took a fast look, but seems a really good starting point!! I'm gonna test your repo this week and come back with the results.
> 
> Thanks for contributing to the DRLM project!
> 
> Regards,
> Didac

Thanks for this project, i was using mondo rescue before, but was abandoned sometime ago and i'm really surprised no one is talking about this project? - Doing a cold boot restore is so useful and convenient - so thanks!
Also using the bash scripting makes its so easy for me to understand.

So yeh let me know of anything useful to add, i will keep adding or changing this docker version as i use it myself and its so useful for me and no doubt other people.

Thanks
David

**Comment by didacog** [comment]
Hello David (@db260179),

I took a closer look at your drlm branch, here my thoughts about it:

- The develop branch must be used as base, docker option will be in   milestone for drlm 2.4.0. version 2.3.0 is almost ready and we are just solving last bugs and adjustments.

- Instead of <pre>make install</pre> a multi stage dockerfile can be used to generate the .deb file in the build phase with all build deps and use it in the final container. I think that may be better and avoids the need of debian system to build the docker image and the need for dependencies like golang (drlm-api) in the build system. 

- I agree that systemd in docker is a pain, going for supervisord then. I've seen that in entrypoint.sh there is stop dhcpd but not the start. Also the drlm-stord service should be started to mount all loopdevices (.dr files). This will be splitted soon to a drlm-api service also, we have to take it in mind.  

NOTE: The host system must have enough loop devices available for drlm to work. so for the documentation we must explain that the loop limit will be set in the host system.

- It's ok to bind to host directories for persistence, for now we depend on host networking, so may be the better option for now, but we must have persistent dirs for:

- /var/lib/drlm/store
- /var/lib/drlm/arch
- /var/log/drlm
- /var/lib/drlm

@proura @NefixEstrada @krbu, anything I missed??

In docker build phase is not possible to mount host dirs, so on install, image upgrades, etc. to keep the database persistent among other things may we better move the .deb install at entrypoint phase to be able to persist everithing is needed in host dirs. Let me know if you have better option.

I agree that a docker-compose will be better to manage the container.

Maybe the first thing to do is to use the develop branch and make PR to it, then we can follow the changes, test,comment, change them until  ready to merge?

For now is what I had time to see and think about it, let me know what do you think. 
To start is a quite bunch of things, isn't it.

Thanks!
Didac

**Comment by NefixEstrada** [comment]
Hello!

The `/etc/drlm` directory should also be mounted as a volume, we don't want to lose our configuration!

All the other things that I thought have already been said. Huge thanks for your work!

Néfix

**Comment by db260179** [comment]
> Hello David (@db260179),
> 
> I took a closer look at your drlm branch, here my thoughts about it:
> 
> * The develop branch must be used as base, docker option will be in   milestone for drlm 2.4.0. version 
2.3.0 is almost ready and we are just solving last bugs and adjustments.

Yep, I now base on the develop branch now

> * Instead of make install a multi stage dockerfile can be used to generate the .deb file in the build phase with all build deps and use it in the final container. I think that may be better and avoids the need of debian system to build the docker image and the need for dependencies like golang (drlm-api) in the build system.

My latest changes now does this - so no development tools needed in final image! Thanks

> * I agree that systemd in docker is a pain, going for supervisord then. I've seen that in entrypoint.sh there is stop dhcpd but not the start.

I will be adding the supervisord soon

The reason behind this is because the dhcpd service will only start when a valid network is added to drlm, otherwise the dhcpd service has no way to start? - using the drlm add-network will make dhcpd start automatically

Also the drlm-stord service should be started to mount all loopdevices (.dr files). This will be splitted soon to a drlm-api service also, we have to take it in mind.

Ok missed that, will add that as a startup service

> 
> NOTE: The host system must have enough loop devices available for drlm to work. so for the documentation we must explain that the loop limit will be set in the host system.

Yeh added to the readme

> 
> * It's ok to bind to host directories for persistence, for now we depend on host networking, so may be the better option for now, but we must have persistent dirs for:
> * /var/lib/drlm/store
> * /var/lib/drlm/arch
> * /var/log/drlm
> * /var/lib/drlm
> 

packaging/docker/run.sh i've added docker volumes for one of these locations, will add the rest  - logging will be redirected via /dev/stdout as we don't store logging in containers

> @proura @NefixEstrada @krbu, anything I missed??

> For now is what I had time to see and think about it, let me know what do you think.
> To start is a quite bunch of things, isn't it.
> 
> Thanks!
> Didac

Yep, i'm working on this part time - my current implementation works for me, but the supervisord will improve control - doing 'docker exec -it drlm_server drlm 'option' works for drlm interaction.

**Comment by didacog** [comment]
Hello David (@db260179), 
Sorry for the late response, I was on vacation and with lot stuff to do at home, with the family, etc.

Seems that the only thing pending is supervisord, isn't it? 

If the initial implementation works, do not hesitate to make a PR with what you have now, and we can open new issues to complete it with the pendings.

Regards!
Didac

**Comment by db260179** [comment]
Hi Didac,
Yeh so will be doing an initial PR, will do a supervisord soon. I will have to submit a bug regarding the
'drlm addclient' using sudo, as currently the sudo user doesnt seem to have enough privilages to make an ssl cert for Rear?

'''
Synchronizing state of rpcbind.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable rpcbind
Can't open /etc/rear/cert/drlm-server.crt for reading, Permission denied
139742752416192:error:0200100D:system library:fopen:Permission denied:../crypto/bio/bss_file.c:72:fopen('/etc/rear/cert/drlm-server.crt','r')
139742752416192:error:2006D002:BIO routines:BIO_new_file:system lib:../crypto/bio/bss_file.c:81:
unable to load certificate
'''

**Comment by didacog** [comment]
Hi @db260179 

Your PR is merged in develop, so I'm closing this issue now. The supervisord addition will be recorded in issue #126 .

Many thanks for your contribution! I hope you can continue helping us improving drlm.

Kind regards!
Didac
