### ISSUE TITLE
ReaR crontab file

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#73]
* Issue type: Discussion/Enhancement
* Impact: Low
* How often it happens: Always
* Brief description of the issue: When ReaR is installed creates a crontab file by default tath checks the layout daily and run a mkrescue if necessary. Is necessary that this is runned by the DRLM/ReaR clients and not from DRLM server? can cause problems or errors ?

* Work-around, if any:

##### DRLM Server information:

* DRLM version: Disaster Recovery Linux Manager 2.2.0-git / 2017-09-20
  
##### DRLM Client information:

* ReaR version: Relax-and-Recover 2.2 / 2017-07-20

**Comment by didacog** [comment]
Well, the question was been posted a while ago but for me the checklayout cron should be disabled from clients at install time (instclient workflow). Does not make sense to have it scheduled in client systems. 

Going further, IMHO we should split our mkbackup run in mkrescue + mkbackup, and run checklayout from drlm before mkrescue to speed up the backup if no changes in layout among other things.

I'll prepare a new issue to discuss on that, because the change is bigger than just disabling it. That could be done right now without any problems and close this issue.

**Comment by proura** [comment]
Hi, It seems that in the latest versions of ReaR no task is created in the crontab. I will close this issue.
